# Generated by Django 5.2 on 2025-04-17 07:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Case Type")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("criminal_person_type", models.CharField(blank=True, max_length=255)),
                (
                    "criminal_location_type",
                    models.CharField(blank=True, max_length=255),
                ),
                ("criminal_item_type", models.CharField(blank=True, max_length=255)),
                (
                    "criminal_mastermind_type",
                    models.CharField(blank=True, max_length=255),
                ),
                ("criminal_victim_type", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="customuser_set",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="customuser_user_set",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_name",
                    models.CharField(max_length=255, verbose_name="Case Name"),
                ),
                (
                    "notebook_description",
                    models.TextField(verbose_name="Notebook Description"),
                ),
                (
                    "initial_description",
                    models.TextField(verbose_name="Initial Description"),
                ),
                (
                    "notebook_image_url",
                    models.URLField(
                        blank=True, max_length=255, verbose_name="Notebook Image URL"
                    ),
                ),
                (
                    "intro_image_url",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        verbose_name="Introduction Image URL",
                    ),
                ),
                ("case_order", models.IntegerField(verbose_name="Order")),
                ("case_difficulty", models.IntegerField(verbose_name="Difficulty")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created"
                    ),
                ),
                (
                    "case_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="detective.casetype",
                        verbose_name="Case Type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dialog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_key", models.CharField(max_length=100)),
                ("text", models.TextField()),
                ("is_entry_node", models.BooleanField(default=False)),
                ("emotion_above", models.IntegerField(default=100)),
                ("emotion_below", models.IntegerField(default=0)),
                ("visit_count", models.IntegerField(default=0)),
                ("is_evidence", models.BooleanField(default=False)),
                ("reaction_description", models.TextField(blank=True)),
                ("time_for_option", models.IntegerField(default=1)),
                ("requires_visits", models.IntegerField(default=0)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dialogs",
                        to="detective.case",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="case",
            name="first_dialogue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="start_cases",
                to="detective.dialog",
                verbose_name="First Dialogue",
            ),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("deep_description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("evidence_value", models.IntegerField(default=0)),
                ("time_to_examine", models.IntegerField(default=0)),
                ("time_to_deep_exam", models.IntegerField(default=0)),
                ("require_deep_search", models.BooleanField(default=False)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="detective.case",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dialog",
            name="evidence_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="detective.item",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="criminal_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases_with_crime_item",
                to="detective.item",
                verbose_name="Crime Item",
            ),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("initial_attitude", models.IntegerField(default=50)),
                ("is_criminal", models.BooleanField(default=False)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persons",
                        to="detective.case",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="detective.person",
            ),
        ),
        migrations.AddField(
            model_name="dialog",
            name="hint_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hinted_in_dialogs",
                to="detective.person",
            ),
        ),
        migrations.AddField(
            model_name="dialog",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dialogs",
                to="detective.person",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="criminal_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="criminal_in_cases",
                to="detective.person",
                verbose_name="Criminal",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="initial_person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases_given",
                to="detective.person",
                verbose_name="Initial Person",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="mastermind_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mastermind_in_cases",
                to="detective.person",
                verbose_name="Mastermind",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="victim_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="victim_in_cases",
                to="detective.person",
                verbose_name="Victim",
            ),
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("deep_description", models.TextField(blank=True)),
                ("map_x", models.IntegerField()),
                ("map_y", models.IntegerField()),
                ("extra_travel_time", models.IntegerField(default=0)),
                ("image_url", models.URLField(blank=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("time_to_examine", models.IntegerField(default=0)),
                ("time_to_deep_exam", models.IntegerField(default=0)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to="detective.case",
                    ),
                ),
                (
                    "required_key_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="places_requiring_key_item",
                        to="detective.item",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="person",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="detective.place",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="detective.place",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="criminal_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases_with_crime_place",
                to="detective.place",
                verbose_name="Crime Location",
            ),
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_game_first_name", models.CharField(max_length=50)),
                ("in_game_last_name", models.CharField(max_length=50)),
                ("title", models.CharField(default="Aspirant", max_length=50)),
                ("avatar_url", models.CharField(max_length=255)),
                (
                    "sign_up_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("num_of_logins", models.IntegerField(default=1)),
                (
                    "last_login_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fk_current_case_id", models.IntegerField(blank=True, null=True)),
                (
                    "fk_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
