# Generated by Django 5.2 on 2025-04-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detective", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="intro_image_url",
            field=models.CharField(
                blank=True,
                help_text="Relativ sökväg under static/, ex: detective/images/cases/1/intro.png",
                max_length=255,
                verbose_name="Intro Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="notebook_image_url",
            field=models.CharField(
                blank=True,
                help_text="Relativ sökväg under static/, ex: detective/images/cases/1/notebook.png",
                max_length=255,
                verbose_name="Notebook Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="image_url",
            field=models.CharField(
                blank=True,
                help_text="Relativ sökväg under static/, ex: detective/images/cases/1/item_x.png",
                max_length=255,
                verbose_name="Item Image URL",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="image_url",
            field=models.CharField(
                blank=True,
                help_text="Relativ sökväg under static/, ex: detective/images/cases/1/.png",
                max_length=255,
                verbose_name="Person Image URL",
            ),
        ),
    ]
