# Generated by Django 5.2 on 2025-04-17 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detective", "0002_alter_case_intro_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dialog",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dialogs",
                to="detective.case",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="detective.case",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="places",
                to="detective.case",
            ),
        ),
    ]
