# Generated by Django 5.2 on 2025-04-17 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detective", "0003_alter_dialog_case_alter_item_case_alter_place_case"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="persons",
                to="detective.case",
            ),
        ),
    ]
